# Generated by Django 5.1.3 on 2024-12-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groqapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
